### ISSUE TITLE
Not working with Vite: ^6.x.x

### ISSUE THREAD

**Issue by necatisarhanli** [module-federation/vite#231]
I implemented this module federation plugin to my vite project but on development its just blank page, there is no log or anything, i also tried to run examples but its same (vite-vite) . remote project not working unless I downgrade vite version to 5 then its starts to render my react page . I checked the issues but couldn't find any solution.

**Comment by gioboa** [comment]
Hi @necatisarhanli thanks for your feedback 
I close this one because this issue is fixed by #229

**Comment by necatisarhanli** [comment]
@gioboa but issue is still there , its not working with vite 6 ,and modelefederation/vite 1.2.0. could you please provide
vite(react)host - vite(react)remote example. I am having hard time to implement it.

**Comment by gioboa** [comment]
We need to release a new version with that update.
cc @ScriptedAlchemy

**Comment by gioboa** [comment]
[1.2.1](https://www.npmjs.com/package/@module-federation/vite/v/1.2.1) is available.
